//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasoExamen.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CasoExamenEntities : DbContext
    {
        public CasoExamenEntities()
            : base("name=CasoExamenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }
        public DbSet<ADMIN> ADMIN { get; set; }
        public DbSet<ASESORIA> ASESORIA { get; set; }
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<PROFESIONAL> PROFESIONAL { get; set; }
        public DbSet<REPORTE> REPORTE { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<VISITA> VISITA { get; set; }
    
        public virtual int SP_CREATE_ACTIVIDAD(Nullable<System.DateTime> v_FECHA_ACT, string v_DESCRIPCION_ACT)
        {
            var v_FECHA_ACTParameter = v_FECHA_ACT.HasValue ?
                new ObjectParameter("V_FECHA_ACT", v_FECHA_ACT) :
                new ObjectParameter("V_FECHA_ACT", typeof(System.DateTime));
    
            var v_DESCRIPCION_ACTParameter = v_DESCRIPCION_ACT != null ?
                new ObjectParameter("V_DESCRIPCION_ACT", v_DESCRIPCION_ACT) :
                new ObjectParameter("V_DESCRIPCION_ACT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_ACTIVIDAD", v_FECHA_ACTParameter, v_DESCRIPCION_ACTParameter);
        }
    
        public virtual int SP_CREATE_ASESORIA(Nullable<System.DateTime> v_FECHA_ASE, string v_DESCRIPCION_ASE)
        {
            var v_FECHA_ASEParameter = v_FECHA_ASE.HasValue ?
                new ObjectParameter("V_FECHA_ASE", v_FECHA_ASE) :
                new ObjectParameter("V_FECHA_ASE", typeof(System.DateTime));
    
            var v_DESCRIPCION_ASEParameter = v_DESCRIPCION_ASE != null ?
                new ObjectParameter("V_DESCRIPCION_ASE", v_DESCRIPCION_ASE) :
                new ObjectParameter("V_DESCRIPCION_ASE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_ASESORIA", v_FECHA_ASEParameter, v_DESCRIPCION_ASEParameter);
        }
    
        public virtual int SP_CREATE_CAPACITACION(Nullable<System.DateTime> v_FECHA_CAP, string v_ASISTENTES_CAP, string v_DESCRIPCION_CAP)
        {
            var v_FECHA_CAPParameter = v_FECHA_CAP.HasValue ?
                new ObjectParameter("V_FECHA_CAP", v_FECHA_CAP) :
                new ObjectParameter("V_FECHA_CAP", typeof(System.DateTime));
    
            var v_ASISTENTES_CAPParameter = v_ASISTENTES_CAP != null ?
                new ObjectParameter("V_ASISTENTES_CAP", v_ASISTENTES_CAP) :
                new ObjectParameter("V_ASISTENTES_CAP", typeof(string));
    
            var v_DESCRIPCION_CAPParameter = v_DESCRIPCION_CAP != null ?
                new ObjectParameter("V_DESCRIPCION_CAP", v_DESCRIPCION_CAP) :
                new ObjectParameter("V_DESCRIPCION_CAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CAPACITACION", v_FECHA_CAPParameter, v_ASISTENTES_CAPParameter, v_DESCRIPCION_CAPParameter);
        }
    
        public virtual int SP_CREATE_CLIENTE(string v_RUT_EMP, string v_NOM_EMP, string v_NOM_REPRE, string v_APE_REPRE, string v_CORREO, string v_DIREC_EMP, string v_NUM_TELEF, Nullable<decimal> v_ID_RUBRO)
        {
            var v_RUT_EMPParameter = v_RUT_EMP != null ?
                new ObjectParameter("V_RUT_EMP", v_RUT_EMP) :
                new ObjectParameter("V_RUT_EMP", typeof(string));
    
            var v_NOM_EMPParameter = v_NOM_EMP != null ?
                new ObjectParameter("V_NOM_EMP", v_NOM_EMP) :
                new ObjectParameter("V_NOM_EMP", typeof(string));
    
            var v_NOM_REPREParameter = v_NOM_REPRE != null ?
                new ObjectParameter("V_NOM_REPRE", v_NOM_REPRE) :
                new ObjectParameter("V_NOM_REPRE", typeof(string));
    
            var v_APE_REPREParameter = v_APE_REPRE != null ?
                new ObjectParameter("V_APE_REPRE", v_APE_REPRE) :
                new ObjectParameter("V_APE_REPRE", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            var v_DIREC_EMPParameter = v_DIREC_EMP != null ?
                new ObjectParameter("V_DIREC_EMP", v_DIREC_EMP) :
                new ObjectParameter("V_DIREC_EMP", typeof(string));
    
            var v_NUM_TELEFParameter = v_NUM_TELEF != null ?
                new ObjectParameter("V_NUM_TELEF", v_NUM_TELEF) :
                new ObjectParameter("V_NUM_TELEF", typeof(string));
    
            var v_ID_RUBROParameter = v_ID_RUBRO.HasValue ?
                new ObjectParameter("V_ID_RUBRO", v_ID_RUBRO) :
                new ObjectParameter("V_ID_RUBRO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CLIENTE", v_RUT_EMPParameter, v_NOM_EMPParameter, v_NOM_REPREParameter, v_APE_REPREParameter, v_CORREOParameter, v_DIREC_EMPParameter, v_NUM_TELEFParameter, v_ID_RUBROParameter);
        }
    
        public virtual int SP_CREATE_PAGO(Nullable<System.DateTime> v_FECHA_PAGO, string v_DESCRIPCION_PAGO, string v_METODO_PAGO, Nullable<decimal> v_ID_EMP)
        {
            var v_FECHA_PAGOParameter = v_FECHA_PAGO.HasValue ?
                new ObjectParameter("V_FECHA_PAGO", v_FECHA_PAGO) :
                new ObjectParameter("V_FECHA_PAGO", typeof(System.DateTime));
    
            var v_DESCRIPCION_PAGOParameter = v_DESCRIPCION_PAGO != null ?
                new ObjectParameter("V_DESCRIPCION_PAGO", v_DESCRIPCION_PAGO) :
                new ObjectParameter("V_DESCRIPCION_PAGO", typeof(string));
    
            var v_METODO_PAGOParameter = v_METODO_PAGO != null ?
                new ObjectParameter("V_METODO_PAGO", v_METODO_PAGO) :
                new ObjectParameter("V_METODO_PAGO", typeof(string));
    
            var v_ID_EMPParameter = v_ID_EMP.HasValue ?
                new ObjectParameter("V_ID_EMP", v_ID_EMP) :
                new ObjectParameter("V_ID_EMP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PAGO", v_FECHA_PAGOParameter, v_DESCRIPCION_PAGOParameter, v_METODO_PAGOParameter, v_ID_EMPParameter);
        }
    
        public virtual int SP_CREATE_PROFESIONAL(string v_NOM_PROF, string v_APELL_PROF, string v_RUT_PROF, string v_CORREO, string v_NUM_TELEF)
        {
            var v_NOM_PROFParameter = v_NOM_PROF != null ?
                new ObjectParameter("V_NOM_PROF", v_NOM_PROF) :
                new ObjectParameter("V_NOM_PROF", typeof(string));
    
            var v_APELL_PROFParameter = v_APELL_PROF != null ?
                new ObjectParameter("V_APELL_PROF", v_APELL_PROF) :
                new ObjectParameter("V_APELL_PROF", typeof(string));
    
            var v_RUT_PROFParameter = v_RUT_PROF != null ?
                new ObjectParameter("V_RUT_PROF", v_RUT_PROF) :
                new ObjectParameter("V_RUT_PROF", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            var v_NUM_TELEFParameter = v_NUM_TELEF != null ?
                new ObjectParameter("V_NUM_TELEF", v_NUM_TELEF) :
                new ObjectParameter("V_NUM_TELEF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PROFESIONAL", v_NOM_PROFParameter, v_APELL_PROFParameter, v_RUT_PROFParameter, v_CORREOParameter, v_NUM_TELEFParameter);
        }
    
        public virtual int SP_CREATE_REPORTE(Nullable<System.DateTime> v_FECHA_REP, string v_DESCRIPCION_REP)
        {
            var v_FECHA_REPParameter = v_FECHA_REP.HasValue ?
                new ObjectParameter("V_FECHA_REP", v_FECHA_REP) :
                new ObjectParameter("V_FECHA_REP", typeof(System.DateTime));
    
            var v_DESCRIPCION_REPParameter = v_DESCRIPCION_REP != null ?
                new ObjectParameter("V_DESCRIPCION_REP", v_DESCRIPCION_REP) :
                new ObjectParameter("V_DESCRIPCION_REP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_REPORTE", v_FECHA_REPParameter, v_DESCRIPCION_REPParameter);
        }
    
        public virtual int SP_CREATE_VISITA(Nullable<System.DateTime> v_FECHA_VIS, string v_DESCRIPCION_VIS, Nullable<decimal> v_ID_PROF_VIS)
        {
            var v_FECHA_VISParameter = v_FECHA_VIS.HasValue ?
                new ObjectParameter("V_FECHA_VIS", v_FECHA_VIS) :
                new ObjectParameter("V_FECHA_VIS", typeof(System.DateTime));
    
            var v_DESCRIPCION_VISParameter = v_DESCRIPCION_VIS != null ?
                new ObjectParameter("V_DESCRIPCION_VIS", v_DESCRIPCION_VIS) :
                new ObjectParameter("V_DESCRIPCION_VIS", typeof(string));
    
            var v_ID_PROF_VISParameter = v_ID_PROF_VIS.HasValue ?
                new ObjectParameter("V_ID_PROF_VIS", v_ID_PROF_VIS) :
                new ObjectParameter("V_ID_PROF_VIS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_VISITA", v_FECHA_VISParameter, v_DESCRIPCION_VISParameter, v_ID_PROF_VISParameter);
        }
    
        public virtual int SP_DELETE_ACTIVIDAD(Nullable<decimal> v_ID_ACTIVIDAD)
        {
            var v_ID_ACTIVIDADParameter = v_ID_ACTIVIDAD.HasValue ?
                new ObjectParameter("V_ID_ACTIVIDAD", v_ID_ACTIVIDAD) :
                new ObjectParameter("V_ID_ACTIVIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ACTIVIDAD", v_ID_ACTIVIDADParameter);
        }
    
        public virtual int SP_DELETE_ASESORIA(Nullable<decimal> v_ID_ASESORIA)
        {
            var v_ID_ASESORIAParameter = v_ID_ASESORIA.HasValue ?
                new ObjectParameter("V_ID_ASESORIA", v_ID_ASESORIA) :
                new ObjectParameter("V_ID_ASESORIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ASESORIA", v_ID_ASESORIAParameter);
        }
    
        public virtual int SP_DELETE_CAPACITACION(Nullable<decimal> v_ID_CAP)
        {
            var v_ID_CAPParameter = v_ID_CAP.HasValue ?
                new ObjectParameter("V_ID_CAP", v_ID_CAP) :
                new ObjectParameter("V_ID_CAP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CAPACITACION", v_ID_CAPParameter);
        }
    
        public virtual int SP_DELETE_CLIENTE(Nullable<decimal> v_ID_EMP)
        {
            var v_ID_EMPParameter = v_ID_EMP.HasValue ?
                new ObjectParameter("V_ID_EMP", v_ID_EMP) :
                new ObjectParameter("V_ID_EMP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CLIENTE", v_ID_EMPParameter);
        }
    
        public virtual int SP_DELETE_PAGO(Nullable<decimal> v_ID_PAGO)
        {
            var v_ID_PAGOParameter = v_ID_PAGO.HasValue ?
                new ObjectParameter("V_ID_PAGO", v_ID_PAGO) :
                new ObjectParameter("V_ID_PAGO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PAGO", v_ID_PAGOParameter);
        }
    
        public virtual int SP_DELETE_PROFESIONAL(Nullable<decimal> v_ID_PROFESIONAL)
        {
            var v_ID_PROFESIONALParameter = v_ID_PROFESIONAL.HasValue ?
                new ObjectParameter("V_ID_PROFESIONAL", v_ID_PROFESIONAL) :
                new ObjectParameter("V_ID_PROFESIONAL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PROFESIONAL", v_ID_PROFESIONALParameter);
        }
    
        public virtual int SP_DELETE_REPORTE(Nullable<decimal> v_ID_REPORTE)
        {
            var v_ID_REPORTEParameter = v_ID_REPORTE.HasValue ?
                new ObjectParameter("V_ID_REPORTE", v_ID_REPORTE) :
                new ObjectParameter("V_ID_REPORTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_REPORTE", v_ID_REPORTEParameter);
        }
    
        public virtual int SP_DELETE_VISITA(Nullable<decimal> v_ID_VISITA)
        {
            var v_ID_VISITAParameter = v_ID_VISITA.HasValue ?
                new ObjectParameter("V_ID_VISITA", v_ID_VISITA) :
                new ObjectParameter("V_ID_VISITA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_VISITA", v_ID_VISITAParameter);
        }
    
        public virtual int SP_UPDATE_ACTIVIDAD(Nullable<decimal> v_ID_ACTIVIDAD, Nullable<System.DateTime> v_FECHA_ACT, string v_DESCRIPCION_ACT)
        {
            var v_ID_ACTIVIDADParameter = v_ID_ACTIVIDAD.HasValue ?
                new ObjectParameter("V_ID_ACTIVIDAD", v_ID_ACTIVIDAD) :
                new ObjectParameter("V_ID_ACTIVIDAD", typeof(decimal));
    
            var v_FECHA_ACTParameter = v_FECHA_ACT.HasValue ?
                new ObjectParameter("V_FECHA_ACT", v_FECHA_ACT) :
                new ObjectParameter("V_FECHA_ACT", typeof(System.DateTime));
    
            var v_DESCRIPCION_ACTParameter = v_DESCRIPCION_ACT != null ?
                new ObjectParameter("V_DESCRIPCION_ACT", v_DESCRIPCION_ACT) :
                new ObjectParameter("V_DESCRIPCION_ACT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_ACTIVIDAD", v_ID_ACTIVIDADParameter, v_FECHA_ACTParameter, v_DESCRIPCION_ACTParameter);
        }
    
        public virtual int SP_UPDATE_ASESORIA(Nullable<decimal> v_ID_ASESORIA, Nullable<System.DateTime> v_FECHA_ASE, string v_DESCRIPCION_ASE)
        {
            var v_ID_ASESORIAParameter = v_ID_ASESORIA.HasValue ?
                new ObjectParameter("V_ID_ASESORIA", v_ID_ASESORIA) :
                new ObjectParameter("V_ID_ASESORIA", typeof(decimal));
    
            var v_FECHA_ASEParameter = v_FECHA_ASE.HasValue ?
                new ObjectParameter("V_FECHA_ASE", v_FECHA_ASE) :
                new ObjectParameter("V_FECHA_ASE", typeof(System.DateTime));
    
            var v_DESCRIPCION_ASEParameter = v_DESCRIPCION_ASE != null ?
                new ObjectParameter("V_DESCRIPCION_ASE", v_DESCRIPCION_ASE) :
                new ObjectParameter("V_DESCRIPCION_ASE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_ASESORIA", v_ID_ASESORIAParameter, v_FECHA_ASEParameter, v_DESCRIPCION_ASEParameter);
        }
    
        public virtual int SP_UPDATE_CAPACITACION(Nullable<decimal> v_ID_CAP, Nullable<System.DateTime> v_FECHA_CAP, string v_ASISTENTES_CAP, string v_DESCRIPCION_CAP)
        {
            var v_ID_CAPParameter = v_ID_CAP.HasValue ?
                new ObjectParameter("V_ID_CAP", v_ID_CAP) :
                new ObjectParameter("V_ID_CAP", typeof(decimal));
    
            var v_FECHA_CAPParameter = v_FECHA_CAP.HasValue ?
                new ObjectParameter("V_FECHA_CAP", v_FECHA_CAP) :
                new ObjectParameter("V_FECHA_CAP", typeof(System.DateTime));
    
            var v_ASISTENTES_CAPParameter = v_ASISTENTES_CAP != null ?
                new ObjectParameter("V_ASISTENTES_CAP", v_ASISTENTES_CAP) :
                new ObjectParameter("V_ASISTENTES_CAP", typeof(string));
    
            var v_DESCRIPCION_CAPParameter = v_DESCRIPCION_CAP != null ?
                new ObjectParameter("V_DESCRIPCION_CAP", v_DESCRIPCION_CAP) :
                new ObjectParameter("V_DESCRIPCION_CAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CAPACITACION", v_ID_CAPParameter, v_FECHA_CAPParameter, v_ASISTENTES_CAPParameter, v_DESCRIPCION_CAPParameter);
        }
    
        public virtual int SP_UPDATE_CLIENTE(Nullable<decimal> v_ID_EMP, string v_RUT_EMP, string v_NOM_EMP, string v_NOM_REPRE, string v_APE_REPRE, string v_CORREO, string v_PASSWORD, string v_DIREC_EMP, string v_NUM_TELEF, Nullable<decimal> v_ID_RUBRO)
        {
            var v_ID_EMPParameter = v_ID_EMP.HasValue ?
                new ObjectParameter("V_ID_EMP", v_ID_EMP) :
                new ObjectParameter("V_ID_EMP", typeof(decimal));
    
            var v_RUT_EMPParameter = v_RUT_EMP != null ?
                new ObjectParameter("V_RUT_EMP", v_RUT_EMP) :
                new ObjectParameter("V_RUT_EMP", typeof(string));
    
            var v_NOM_EMPParameter = v_NOM_EMP != null ?
                new ObjectParameter("V_NOM_EMP", v_NOM_EMP) :
                new ObjectParameter("V_NOM_EMP", typeof(string));
    
            var v_NOM_REPREParameter = v_NOM_REPRE != null ?
                new ObjectParameter("V_NOM_REPRE", v_NOM_REPRE) :
                new ObjectParameter("V_NOM_REPRE", typeof(string));
    
            var v_APE_REPREParameter = v_APE_REPRE != null ?
                new ObjectParameter("V_APE_REPRE", v_APE_REPRE) :
                new ObjectParameter("V_APE_REPRE", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            var v_PASSWORDParameter = v_PASSWORD != null ?
                new ObjectParameter("V_PASSWORD", v_PASSWORD) :
                new ObjectParameter("V_PASSWORD", typeof(string));
    
            var v_DIREC_EMPParameter = v_DIREC_EMP != null ?
                new ObjectParameter("V_DIREC_EMP", v_DIREC_EMP) :
                new ObjectParameter("V_DIREC_EMP", typeof(string));
    
            var v_NUM_TELEFParameter = v_NUM_TELEF != null ?
                new ObjectParameter("V_NUM_TELEF", v_NUM_TELEF) :
                new ObjectParameter("V_NUM_TELEF", typeof(string));
    
            var v_ID_RUBROParameter = v_ID_RUBRO.HasValue ?
                new ObjectParameter("V_ID_RUBRO", v_ID_RUBRO) :
                new ObjectParameter("V_ID_RUBRO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CLIENTE", v_ID_EMPParameter, v_RUT_EMPParameter, v_NOM_EMPParameter, v_NOM_REPREParameter, v_APE_REPREParameter, v_CORREOParameter, v_PASSWORDParameter, v_DIREC_EMPParameter, v_NUM_TELEFParameter, v_ID_RUBROParameter);
        }
    
        public virtual int SP_UPDATE_PAGO(Nullable<decimal> v_ID_PAGO, Nullable<System.DateTime> v_FECHA_PAGO, string v_DESCRIPCION_PAGO, string v_METODO_PAGO, Nullable<decimal> v_ID_EMP)
        {
            var v_ID_PAGOParameter = v_ID_PAGO.HasValue ?
                new ObjectParameter("V_ID_PAGO", v_ID_PAGO) :
                new ObjectParameter("V_ID_PAGO", typeof(decimal));
    
            var v_FECHA_PAGOParameter = v_FECHA_PAGO.HasValue ?
                new ObjectParameter("V_FECHA_PAGO", v_FECHA_PAGO) :
                new ObjectParameter("V_FECHA_PAGO", typeof(System.DateTime));
    
            var v_DESCRIPCION_PAGOParameter = v_DESCRIPCION_PAGO != null ?
                new ObjectParameter("V_DESCRIPCION_PAGO", v_DESCRIPCION_PAGO) :
                new ObjectParameter("V_DESCRIPCION_PAGO", typeof(string));
    
            var v_METODO_PAGOParameter = v_METODO_PAGO != null ?
                new ObjectParameter("V_METODO_PAGO", v_METODO_PAGO) :
                new ObjectParameter("V_METODO_PAGO", typeof(string));
    
            var v_ID_EMPParameter = v_ID_EMP.HasValue ?
                new ObjectParameter("V_ID_EMP", v_ID_EMP) :
                new ObjectParameter("V_ID_EMP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PAGO", v_ID_PAGOParameter, v_FECHA_PAGOParameter, v_DESCRIPCION_PAGOParameter, v_METODO_PAGOParameter, v_ID_EMPParameter);
        }
    
        public virtual int SP_UPDATE_PROFESIONAL(Nullable<decimal> v_ID_PROFESIONAL, string v_NOM_PROF, string v_APELL_PROF, string v_RUT_PROF, string v_CORREO, string v_PASSWORD_PROF, string v_NUM_TELEF)
        {
            var v_ID_PROFESIONALParameter = v_ID_PROFESIONAL.HasValue ?
                new ObjectParameter("V_ID_PROFESIONAL", v_ID_PROFESIONAL) :
                new ObjectParameter("V_ID_PROFESIONAL", typeof(decimal));
    
            var v_NOM_PROFParameter = v_NOM_PROF != null ?
                new ObjectParameter("V_NOM_PROF", v_NOM_PROF) :
                new ObjectParameter("V_NOM_PROF", typeof(string));
    
            var v_APELL_PROFParameter = v_APELL_PROF != null ?
                new ObjectParameter("V_APELL_PROF", v_APELL_PROF) :
                new ObjectParameter("V_APELL_PROF", typeof(string));
    
            var v_RUT_PROFParameter = v_RUT_PROF != null ?
                new ObjectParameter("V_RUT_PROF", v_RUT_PROF) :
                new ObjectParameter("V_RUT_PROF", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            var v_PASSWORD_PROFParameter = v_PASSWORD_PROF != null ?
                new ObjectParameter("V_PASSWORD_PROF", v_PASSWORD_PROF) :
                new ObjectParameter("V_PASSWORD_PROF", typeof(string));
    
            var v_NUM_TELEFParameter = v_NUM_TELEF != null ?
                new ObjectParameter("V_NUM_TELEF", v_NUM_TELEF) :
                new ObjectParameter("V_NUM_TELEF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PROFESIONAL", v_ID_PROFESIONALParameter, v_NOM_PROFParameter, v_APELL_PROFParameter, v_RUT_PROFParameter, v_CORREOParameter, v_PASSWORD_PROFParameter, v_NUM_TELEFParameter);
        }
    
        public virtual int SP_UPDATE_REPORTE(Nullable<decimal> v_ID_REPORTE, Nullable<System.DateTime> v_FECHA_REP, string v_DESCRIPCION_REP)
        {
            var v_ID_REPORTEParameter = v_ID_REPORTE.HasValue ?
                new ObjectParameter("V_ID_REPORTE", v_ID_REPORTE) :
                new ObjectParameter("V_ID_REPORTE", typeof(decimal));
    
            var v_FECHA_REPParameter = v_FECHA_REP.HasValue ?
                new ObjectParameter("V_FECHA_REP", v_FECHA_REP) :
                new ObjectParameter("V_FECHA_REP", typeof(System.DateTime));
    
            var v_DESCRIPCION_REPParameter = v_DESCRIPCION_REP != null ?
                new ObjectParameter("V_DESCRIPCION_REP", v_DESCRIPCION_REP) :
                new ObjectParameter("V_DESCRIPCION_REP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_REPORTE", v_ID_REPORTEParameter, v_FECHA_REPParameter, v_DESCRIPCION_REPParameter);
        }
    
        public virtual int SP_UPDATE_VISITA(Nullable<decimal> v_ID_VISITA, Nullable<System.DateTime> v_FECHA_VIS, string v_DESCRIPCION_VIS, Nullable<decimal> v_ID_PROF_VIS)
        {
            var v_ID_VISITAParameter = v_ID_VISITA.HasValue ?
                new ObjectParameter("V_ID_VISITA", v_ID_VISITA) :
                new ObjectParameter("V_ID_VISITA", typeof(decimal));
    
            var v_FECHA_VISParameter = v_FECHA_VIS.HasValue ?
                new ObjectParameter("V_FECHA_VIS", v_FECHA_VIS) :
                new ObjectParameter("V_FECHA_VIS", typeof(System.DateTime));
    
            var v_DESCRIPCION_VISParameter = v_DESCRIPCION_VIS != null ?
                new ObjectParameter("V_DESCRIPCION_VIS", v_DESCRIPCION_VIS) :
                new ObjectParameter("V_DESCRIPCION_VIS", typeof(string));
    
            var v_ID_PROF_VISParameter = v_ID_PROF_VIS.HasValue ?
                new ObjectParameter("V_ID_PROF_VIS", v_ID_PROF_VIS) :
                new ObjectParameter("V_ID_PROF_VIS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_VISITA", v_ID_VISITAParameter, v_FECHA_VISParameter, v_DESCRIPCION_VISParameter, v_ID_PROF_VISParameter);
        }
    }
}
