//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasoExamen.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public decimal ID_EMP { get; set; }
        public string RUT_EMP { get; set; }
        public string NOM_EMP { get; set; }
        public string NOM_REPRE { get; set; }
        public string APE_REPRE { get; set; }
        public string CORREO { get; set; }
        public string PASSWORD { get; set; }
        public string DIREC_EMP { get; set; }
        public string NUM_TELEF { get; set; }
        public decimal ID_RUBRO { get; set; }
    
        public virtual RUBRO RUBRO { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
