//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasoExamen.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public decimal ID_VISITA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_PROF { get; set; }
    
        public virtual PROFESIONAL PROFESIONAL { get; set; }
    }
}
